version: "2"

services:
  tf-jupyter-golang:
    image: tf-jupyter-golang
    command: sleep infinity
    volumes:
      - .:/go/src/tfkg:delegated
  tf-jupyter-golang-gpu:
    image: tf-jupyter-golang
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - .:/go/src/tfkg:delegated