version: "2"

services:
  tf-jupyter-golang:
    build:
      context: ./docker/tf-jupyter-golang
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - .:/tfkg
      - .:/go/src/tfkg